### ISSUE TITLE
Getting errors when interacting with PHPmyadmin

### ISSUE THREAD

**Issue by Gryph667** [april-knights/Squire#32]
**Describe the bug**
Getting errors on nearly every table on display via PHPMyAdmin

Knight:

Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2079: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'squiretestone',
string 'knight',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `knight`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'squiretestone',
string 'knight',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `knight`',
NULL,
NULL,
)

**Comment by LeoVerto** [comment]
Pretty sure this isn't a problem with Squire. I suggest you try reinstalling PMA.

**Comment by Gryph667** [comment]
So use 

sudo system remove pma
sudo system install pma

**Comment by Gryph667** [comment]
@LeoVerto can you confirm the commands?

**Comment by Gryph667** [comment]
Only happening on digital ocean db, doesn't seem to be affecting application and will be non issue once it's pointing to AprilKnightsOps correctly
