### ISSUE TITLE
Failure to automatically register reddit account

### ISSUE THREAD

**Issue by Creepachu** [april-knights/Squire#68]
Following this link
https://squire.aprilknights.org/
And allowing squire to access my reddit account returns me to the original page with a small white text box in the top left quarter of the screen saying "user not registered"

1. Click link
2. Press "Reddit Login"
3. Allow squire permissions requested
4. Witness

Using Opera, if it matters. Will try on chrome and update.
UPDATE: Does not work on chrome or with any of my alts

**Comment by Gryph667** [comment]
This is expected behaviour in the instance where a user is not yet created in the system correctly or at all. In this scenario, Knight will need to get in touch with a Councilor or above to have their account created.
