### ISSUE TITLE
Knight Edit form throws 500 server error for names with unicode symbols

### ISSUE THREAD

**Issue by LadyVulcan** [april-knights/Squire#81]
**Describe the bug**
Discord names can include unicode symbols such as "★Mateo★#1900", which our Knight edit form does not support.

**To Reproduce**
1. Go to the profile edit screen
2. Enter a valid Discord name such as "★Mateo★#1900"
3. Click on 'submit'
4. See error: 500

**Expected behavior**
I'd like the edit screen to accept the input. Even if we can't store the wider unicode alphabet, we should sanitize the inputs and include an asterisk or some small marker to indicate that the name was sanitized for database entry.

**Screenshots**
![image](https://user-images.githubusercontent.com/11993633/177866019-5a934c9b-9012-4441-a214-5cd683c9c0cd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Old man yells at cloud: Why do these pesky whippersnappers want stars in their username anyway?

**Comment by Gryph667** [comment]
This is a known issue, from when creating Brie's account. This is a result of MySQL not permitting these characters. Discord names have to be entered with the unicode removed/replaced. This is a contributing factor to DiscordID being a field added to the DB.

**Comment by Gryph667** [comment]
Collation for dbo.knight.dname changed to utf8mb4_unicode_ci. Issue resolved.
